name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: "Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)"
        required: false
        default: false
jobs:
  build-test:
    strategy:
      matrix:
        config:
          # - os: ubuntu-latest
          #   platform: linux-x64-soft
          #   base_flags: -DSTREFLOP_SOFT=ON
          # - os: ubuntu-latest
          #   platform: linux-x64-sse
          #   base_flags:
          # - os: ubuntu-latest
          #   platform: linux-x64-sse-no-denormals
          #   base_flags: -DSTREFLOP_NO_DENORMALS=ON
          # - os: ubuntu-latest
          #   platform: linux-x64-x87
          #   base_flags:
          # - os: ubuntu-latest
          #   platform: linux-x64-x87-no-denormals
          #   base_flags: -DSTREFLOP_NO_DENORMALS=ON
          - os: windows-latest
            platform: windows-x64-sse
            base_flags:
          # - os: windows-latest
          #   platform: windows-x64-sse-no-denormals
          #   base_flags: -DSTREFLOP_NO_DENORMALS=ON
          # - os: windows-latest
          #   platform: windows-x64-x87
          #   base_flags:
          # - os: windows-latest
          #   platform: windows-x64-x87-no-denormals
          #   base_flags: -DSTREFLOP_NO_DENORMALS=ON
          # - os: macos-13
          #   platform: macos-x64-sse
          #   base_flags:
          # - os: macos-13
          #   platform: macos-x64-sse-no-denormals
          #   base_flags: -DSTREFLOP_NO_DENORMALS=ON
          # - os: macos-latest
          #   platform: macos-arm64-neon
          #   base_flags:
          # - os: macos-latest
          #   platform: macos-arm64-neon-no-denormals
          #   base_flags: -DSTREFLOP_NO_DENORMALS=ON

    runs-on: ${{ matrix.config.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Build arithmetic test
        #run: make ${{ matrix.config.base_flags }} arithmeticTest
        run: |
          mkdir build
          cd build
          cmake ${{ matrix.config.base_flags}} ..
          cmake --build .

      - name: Run arithmetic test
        run: cd build && ./arithmeticTest ../result-${{ matrix.config.platform }}

      - name: Setup debug SSH
        # if: ${{ failure() && github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
        uses: mxschmitt/action-tmate@v3

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: results-${{ matrix.config.platform }}
          path: result-${{ matrix.config.platform }}*
  # build-test-linux-arm64-qemu:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: sandervocke/setup-qemu-container@v1
  #       with:
  #         container: gcc:latest
  #         arch: arm64
  #     - uses: sandervocke/setup-shell-wrapper@v1
  #
  #     - name: Build and run arithmetic test
  #       shell: run-in-container.sh {0}
  #       run: |
  #         make STREFLOP_NEON=1 arithmeticTest
  #         ./arithmeticTest result-linux-arm64-neon
  #
  #     - name: Upload results
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: results-linux-arm64-neon
  #         path: result-linux-arm64-neon_*
  #
  # build-test-linux-arm64-no-denormals-qemu:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: sandervocke/setup-qemu-container@v1
  #       with:
  #         container: gcc:latest
  #         arch: arm64
  #     - uses: sandervocke/setup-shell-wrapper@v1
  #
  #     - name: Build and run arithmetic test
  #       shell: run-in-container.sh {0}
  #       run: |
  #         make STREFLOP_NEON=1 STREFLOP_NO_DENORMALS=1 arithmeticTest
  #         ./arithmeticTest result-linux-arm64-neon-no-denormals
  #
  #     - name: Upload results
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: results-linux-arm64-neon-no-denormals
  #         path: result-linux-arm64-neon-no-denormals*

  compare-results:
    needs: [
        build-test,
        # build-test-linux-arm64-qemu,
        # build-test-linux-arm64-no-denormals-qemu,
      ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download all results
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Display structure of downloaded files
        run: ls -Rlah artifacts

      - name: Build compare_floats
        run: make compareFloats

      - name: Compare results
        run: |
          ./compareFloats \
          artifacts/results-linux-x64-soft/result-linux-x64-soft \
          artifacts/results-linux-x64-sse/result-linux-x64-sse \
          artifacts/results-linux-x64-x87/result-linux-x64-x87 \
          artifacts/results-linux-arm64-neon/result-linux-arm64-neon \
          artifacts/results-windows-x64-sse/result-windows-x64-sse \
          artifacts/results-windows-x64-x87/result-windows-x64-x87 \
          artifacts/results-macos-x64-sse/result-macos-x64-sse \
          artifacts/results-macos-arm64-neon/result-macos-arm64-neon

      - name: Compare results (No Denormals)
        run: |
          echo "Software Float (With denormals) vs Linux-x64-SSE (No denormals)"
          ./compareFloats \
          artifacts/results-linux-x64-soft/result-linux-x64-soft \
          artifacts/results-linux-x64-sse-no-denormals/result-linux-x64-sse-no-denormals
          echo
          echo
          echo
          ./compareFloats \
          artifacts/results-linux-x64-sse-no-denormals/result-linux-x64-sse-no-denormals \
          artifacts/results-linux-x64-x87-no-denormals/result-linux-x64-x87-no-denormals \
          artifacts/results-linux-arm64-neon-no-denormals/result-linux-arm64-neon-no-denormals \
          artifacts/results-windows-x64-sse-no-denormals/result-windows-x64-sse-no-denormals \
          artifacts/results-windows-x64-x87-no-denormals/result-windows-x64-x87-no-denormals \
          artifacts/results-macos-x64-sse-no-denormals/result-macos-x64-sse-no-denormals \
          artifacts/results-macos-arm64-neon-no-denormals/result-macos-arm64-neon-no-denormals

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: float_comparison.log
          path: float_comparison.log
