name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-test-matrix:
    strategy:
      matrix:
        include:
          # Linux x64 builds
          # - os: ubuntu-latest
          #   platform: linux-x64-soft
          #   build_flags: STREFLOP_SOFT=1
          - os: ubuntu-latest
            platform: linux-x64-sse
            build_flags: STREFLOP_SSE=1

          # Windows x64 builds
          # - os: windows-latest
          #   platform: windows-x64-soft
          #   build_flags: STREFLOP_SOFT=1
          - os: windows-latest
            platform: windows-x64-sse
            build_flags: STREFLOP_SSE=1

          # macOS x64 builds
          # - os: macos-13
          #   platform: macos-x64-soft
          #   build_flags: STREFLOP_SOFT=1
          - os: macos-13
            platform: macos-x64-sse
            build_flags: STREFLOP_SSE=1

          # macOS ARM64 builds
          # - os: macos-latest
          #   platform: macos-arm64-soft
          #   build_flags: STREFLOP_SOFT=1
          - os: macos-latest
            platform: macos-arm64-neon
            build_flags: STREFLOP_NEON=1

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up environment
        run: echo "PLATFORM=${{ matrix.platform }}" >> $GITHUB_ENV
        shell: bash

      - name: Build arithmetic test
        run: make ${{ matrix.build_flags }} arithmeticTest

      - name: Run arithmetic test
        run: ./arithmeticTest result-${{ env.PLATFORM }}

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: results-${{ env.PLATFORM }}
          path: result-${{ env.PLATFORM }}*

  compare-results:
    needs: build-test-matrix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download all results
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Display structure of downloaded files
        run: ls -R artifacts

      - name: Build compare_floats
        run: make compare_floats

      - name: Compare results
        run: |
          ./compare_floats \
          artifacts/results-linux-x64/result-linux-x64 \
          artifacts/results-windows-x64/result-windows-x64 \
          artifacts/results-macos-x64/result-macos-x64 \
          artifacts/results-macos-arm64/result-macos-arm64
