name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-test-matrix:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux-x64-sse
            build_flags: STREFLOP_SSE=1
          - os: ubuntu-latest
            platform: linux-x64-x87
            build_flags: STREFLOP_X87=1
          - os: windows-latest
            platform: windows-x64-sse
            build_flags: STREFLOP_SSE=1
          - os: windows-latest
            platform: windows-x64-x87
            build_flags: STREFLOP_X87=1
          - os: macos-13
            platform: macos-x64-sse
            build_flags: STREFLOP_SSE=1
          - os: macos-13
            platform: macos-x64-x87
            build_flags: STREFLOP_x87=1
          - os: macos-latest
            platform: macos-arm64-neon
            build_flags: STREFLOP_NEON=1

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Build arithmetic test
        run: make ${{ matrix.build_flags }} arithmeticTest

      - name: Run arithmetic test
        run: ./arithmeticTest result-${{ matrix.platform }}

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: results-${{ matrix.platform }}
          path: result-${{ matrix.platform }}*

  build-test-linux-arm64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: sandervocke/setup-qemu-container@v1
        with:
          container: gcc:latest
          arch: arm64
      - uses: sandervocke/setup-shell-wrapper@v1

      - name: Build and run arithmetic test
        shell: run-in-container.sh {0}
        run: |
          make STREFLOP_NEON=1 arithmeticTest
          ./arithmeticTest result-linux-arm64-neon

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: results-linux-arm64-neon
          path: result-linux-arm64-neon*

  compare-results:
    needs: [build-test-matrix, build-test-linux-arm64]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download all results
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Display structure of downloaded files
        run: ls -Rlah artifacts

      - name: Build compare_floats
        run: make compareFloats

      - name: Compare results
        run: |
          ./compareFloats \
          artifacts/results-linux-x64-sse/result-linux-x64-sse \
          artifacts/results-windows-x64-sse/result-windows-x64-sse \
          artifacts/results-macos-x64-sse/result-macos-x64-sse \
          artifacts/results-linux-arm64-neon/result-linux-arm64-neon \
          artifacts/results-macos-arm64-neon/result-macos-arm64-neon
